/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComicCard: typeof import('./src/components/comic-card.vue')['default']
    DownloadQueuePanel: typeof import('./src/components/download-queue-panel.vue')['default']
    EpubReader: typeof import('./src/components/epub-reader.vue')['default']
    ImageReader: typeof import('./src/components/image-reader.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    NTree: typeof import('naive-ui')['NTree']
    PdfReader: typeof import('./src/components/pdf-reader.vue')['default']
    Provider: typeof import('./src/components/setting/provider.vue')['default']
    ReaderControls: typeof import('./src/components/reader-controls.vue')['default']
    ResourceBrowser: typeof import('./src/components/resource-browser.vue')['default']
    ResponsiveVirtualGrid: typeof import('./src/components/responsive-virtual-grid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VideoCard: typeof import('./src/components/video-card.vue')['default']
    VirtualGrid: typeof import('./src/components/virtual-grid.vue')['default']
  }
}
