name: Build Electron App

on:
  push:
    tags:
      - 'v*' # 只有打 tag 时触发构建，如 v1.0.0
  pull_request:
    branches: [main, master]

env:
  NODE_VERSION: '18'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # 如果需要特定架构，可以添加：
        # include:
        #   - os: ubuntu-latest
        #     arch: x64
        #   - os: macos-latest
        #     arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the app (如果需要)
        run: npm run build || echo "No build script found"

      - name: Package Electron app
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            npm run package:win || npm run package || npx electron-builder --win
          elif [ "$RUNNER_OS" == "macOS" ]; then
            npm run package:mac || npm run package || npx electron-builder --mac
          else
            npm run package:linux || npm run package || npx electron-builder --linux
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-build-${{ matrix.os }}
          path: |
            dist/
            build/
            release/
          retention-days: 7

  # 可选：创建 GitHub Release
  create-release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: List downloaded files
        run: find . -name '*' -type f

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/*.exe
            **/*.dmg
            **/*.AppImage
            **/*.deb
            **/*.rpm
          body: |
            Automated release for ${{ github.ref_name }}

            ### 下载
            - **Windows**: `.exe` 安装包
            - **macOS**: `.dmg` 磁盘映像
            - **Linux**: `.AppImage` 和 `.deb` 包
